from typing import Dict

EXERCISE_CATALOG: Dict[str, dict] = {
    "01": {
        "key": "bending_knee_no_support_seated",
        "name": "Bending the knee without support while sitting",
        "category": "lower_left", 
        "session": 2,
        "image": "assets/images/Bending the knee without support while sitting.png",
    },
    "02": {
        "key": "bending_knee_with_support_seated",
        "name": "Bending the knee with support while sitting",
        "category": "lower_right",
        "session": 1,
        "image": "assets/images/Bending the knee with support while sitting.png",
    },
    "03": {
        "key": "lift_extended_leg_supine",
        "name": "Lift the extended leg",
        "category": "lower_left",
        "session": 1,
        "image": "assets/images/Lift the extended leg.png",
    },
    "04": {
        "key": "bending_knee_bed_support_supine",
        "name": "Bending the knee with bed support",
        "category": "lower_right",
        "session": 1,
        "image": "assets/images/Bending the knee with bed support.png",
    },
    "05": {
        "key": "bending_knee_no_support_seated",
        "name": "Bending the knee without support while sitting",
        "category": "lower_left",
        "session": 2,
        "image": "assets/images/Bending the knee without support while sitting.png",
    },
    "06": {
        "key": "bending_knee_with_support_seated",
        "name": "Bending the knee with support while sitting",
        "category": "lower_right",
        "session": 2,
        "image": "assets/images/Bending the knee with support while sitting.png",
    },
    "07": {
        "key": "lift_extended_leg_supine",
        "name": "Lift the extended leg",
        "category": "lower_left",
        "session": 2,
        "image": "assets/images/Lift the extended leg.png",
    },
    "08": {
        "key": "bending_knee_bed_support_supine",
        "name": "Bending the knee with bed support",
        "category": "lower_right",
        "session": 2,
        "image": "assets/images/Bending the knee with bed support.png",
    },
    "09": {
        "key": "shoulder_flexion_seated",
        "name": "Shoulder flexion",
        "category": "upper_left",
        "session": 1,
        "image": "assets/images/Shoulder flexion seated.png",
    },
    "10": {
        "key": "horizontal_weighted_openings_standing",
        "name": "Horizontal weighted openings",
        "category": "upper_right",
        "session": 1,
        "image": "assets/images/Horizontal weighted openings standing.png",
    },
    "11": {
        "key": "external_rotation_shoulders_elastic",
        "name": "External rotation of shoulders with elastic band",
        "category": "upper_left",
        "session": 1,
        "image": "assets/images/External rotation of shoulders with elastic band.png",
    },
    "12": {
        "key": "circular_pendulum_standing",
        "name": "Circular pendulum",
        "category": "upper_right",
        "session": 1,
        "image": "assets/images/Circular pendulum standing.png",
    },
    "13": {
        "key": "shoulder_flexion_seated",
        "name": "Shoulder flexion",
        "category": "upper_left",
        "session": 2,
        "image": "assets/images/Shoulder flexion seated.png",
    },
    "14": {
        "key": "horizontal_weighted_openings_standing",
        "name": "Horizontal weighted openings",
        "category": "upper_right",
        "session": 2,
        "image": "assets/images/Horizontal weighted openings standing.png",
    },
    "15": {
        "key": "external_rotation_shoulders_elastic",
        "name": "External rotation of shoulders with elastic band",
        "category": "upper_left",
        "session": 2,
        "image": "assets/images/External rotation of shoulders with elastic band.png",
    },
    "16": {
        "key": "circular_pendulum_standing",
        "name": "Circular pendulum",
        "category": "upper_right",
        "session": 2,
        "image": "assets/images/Circular pendulum standing.png",
    },
}
